from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(UserType)
admin.site.register(WorkGroup)
admin.site.register(Professions)
admin.site.register(Worker)
admin.site.register(City)
admin.site.register(Service)
admin.site.register(CostOfService)
admin.site.register(Comments)
admin.site.register(WorkerRating)
admin.site.register(Country)
admin.site.register(Region)
admin.site.register(News)
admin.site.register(JobOrder)
admin.site.register(JobComposition)
admin.site.register(Attacment)
admin.site.register(Message)
admin.site.register(Dialog)
admin.site.register(MessageExpo)
admin.site.register(JobResponse)
