# Generated by Django 3.1.2 on 2020-10-24 14:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.FileField(blank=True, null=True, upload_to='media/attach/', verbose_name='Изображение')),
                ('resizePath', models.FileField(blank=True, null=True, upload_to='media/resizeattach/', verbose_name='Изображение')),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('indexName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Не указано', max_length=100)),
                ('vatnumber', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Изображение')),
                ('phonenumber', models.CharField(max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('block', models.BooleanField(default=False)),
                ('lastOnline', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последний онлайн')),
                ('idCity', models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('image', models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.attacment')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Не указано', max_length=100)),
                ('vatnumber', models.CharField(max_length=12)),
                ('phonenumber', models.CharField(max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmCodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('workpermit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idUser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Участник_1', to=settings.AUTH_USER_MODEL, verbose_name='Участник_1')),
                ('idUser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Участник_2', to=settings.AUTH_USER_MODEL, verbose_name='Участник_2')),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date', models.DateTimeField(default=datetime.date(1900, 1, 1), verbose_name='Дата проведения работ')),
                ('enddate', models.DateTimeField(default=datetime.date(1900, 1, 1), verbose_name='Дата окончания работ')),
                ('place', models.CharField(max_length=100)),
                ('responseCount', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('jobOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('indexName', models.CharField(max_length=100)),
                ('workerСount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Количество рабочих')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block', models.BooleanField(default=False)),
                ('name', models.CharField(default='Не указано', max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('lastname', models.CharField(max_length=100)),
                ('haveIP', models.BooleanField(default=False)),
                ('haveShengen', models.BooleanField(default=False)),
                ('haveIntPass', models.BooleanField(default=False)),
                ('readytotravel', models.BooleanField(default=False)),
                ('haveInstrument', models.BooleanField(default=False)),
                ('fsocheck', models.BooleanField(default=False)),
                ('workpermit', models.BooleanField(default=False)),
                ('datacheck', models.BooleanField(default=False)),
                ('sex', models.BooleanField(default=True)),
                ('personaldataisallowed', models.BooleanField(default=False)),
                ('publishdata', models.BooleanField(default=False)),
                ('Description', models.TextField()),
                ('birthday', models.DateField(default=None, null=True, verbose_name=datetime.date)),
                ('Experiencewith', models.DateField(null=True, verbose_name=datetime.date)),
                ('experience', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение')),
                ('lastOnline', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последний онлайн')),
                ('phonenumber', models.CharField(max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('idCity', models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('image', models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.attacment')),
                ('nationality', models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('professions', models.ManyToManyField(to='main.Professions')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/attach/', verbose_name='Изображение')),
                ('resizeFile', models.FileField(blank=True, null=True, upload_to='media/resizeattach/', verbose_name='Изображение')),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Оценка')),
                ('commentsCount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Количество комментариев')),
                ('idWorker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.DecimalField(decimal_places=0, max_digits=2)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=None, null=True, verbose_name=datetime.date)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
        migrations.AddField(
            model_name='professions',
            name='idWorkGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workgroup'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('link', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('block', models.BooleanField(default=False)),
                ('imagelink', models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.attacment')),
            ],
        ),
        migrations.CreateModel(
            name='MessageExpo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('subject', models.TextField(verbose_name='Тема')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('idDialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dialog', to='main.dialog', verbose_name='Dialog')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='main.joborder', verbose_name='Order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ПолучательСообщения', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ОтправительСообщения', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('subject', models.TextField(verbose_name='Тема')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments', verbose_name='ссылка на комментарий')),
                ('jobresponse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobresponse', verbose_name='ссылка на отклик')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Получатель', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Отправитель', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
        ),
        migrations.AddField(
            model_name='jobresponse',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker'),
        ),
        migrations.CreateModel(
            name='JobComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('jobOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.joborder')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.professions')),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='lastMessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Последнее_сообщение', to='main.messageexpo', verbose_name='Последнее_сообщение'),
        ),
        migrations.CreateModel(
            name='CostOfService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service')),
                ('idWorker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='idProf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.professions', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='comments',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='comments',
            name='idWorker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker', to='main.worker', verbose_name='Работник'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default='00000000000000000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='main.region'),
        ),
    ]
